### ISSUE TITLE
Improve versioning

### ISSUE THREAD

**Issue by Brendon-Hablutzel** [Brendon-Hablutzel/ncsu_courses#5]
Improve the versioning by moving version to a separate file (VERSION), reading from that in \_\_init\_\_.py and setting \_\_version\_\_ to it, and then get the version dynamically in pyproject.toml. Also, check for version changes in GitHu  actions.

### Tasks

- [ ] Move version to separate file and read from that in __init__.py
- [ ] Read version in pyproject.toml
- [ ] Add a check to the GitHub Actions workflow

**Comment by Brendon-Hablutzel** [comment]
Fix by simply not publishing to PyPI in github actions. Will use a periodic release-based system instead.
